name: 'Deploy Solution'
description: 'Deploy a managed solution to a Power Platform environment'
inputs:
  environment-url:
    description: 'Power Platform environment URL'
    required: true
  client-id:
    description: 'Azure AD application client ID'
    required: true
  client-secret:
    description: 'Azure AD application client secret'
    required: true
  tenant-id:
    description: 'Azure AD tenant ID'
    required: true
  solution-name:
    description: 'Name of the solution to deploy'
    required: true
  solution-source-folder:
    description: 'Source folder containing the solution structure (solutions/)'
    required: true
    default: 'solutions/'
  upgrade-mode:
    description: 'Deployment mode: "update" (default, keeps deleted components) or "upgrade" (removes deleted components)'
    required: false
    default: 'update'

runs:
  using: 'composite'
  steps:
    - name: Install Power Platform CLI
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Verify managed solution exists
      shell: pwsh
      run: |
        $managedPath = "${{ inputs.solution-source-folder }}/${{ inputs.solution-name }}/managed/${{ inputs.solution-name }}_managed.zip"
        if (Test-Path $managedPath) {
          Write-Host "✅ Found managed solution: $managedPath"
        } else {
          Write-Host "❌ Managed solution not found: $managedPath"
          Write-Host "Available files in ${{ inputs.solution-source-folder }}/${{ inputs.solution-name }}/managed/:"
          Get-ChildItem "${{ inputs.solution-source-folder }}/${{ inputs.solution-name }}/managed/" -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "  - $($_.Name)" }
          exit 1
        }

    - name: Import MANAGED solution (Update Mode)
      if: inputs.upgrade-mode == 'update'
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{ inputs.environment-url }}
        app-id: ${{ inputs.client-id }}
        client-secret: ${{ inputs.client-secret }}
        tenant-id: ${{ inputs.tenant-id }}
        solution-file: ${{ inputs.solution-source-folder }}/${{ inputs.solution-name }}/managed/${{ inputs.solution-name }}_managed.zip
        force-overwrite: true
        publish-changes: true

    - name: Import solution with upgrade (Upgrade Mode)
      if: inputs.upgrade-mode == 'upgrade'
      uses: microsoft/powerplatform-actions/import-solution@v1
      with:
        environment-url: ${{ inputs.environment-url }}
        app-id: ${{ inputs.client-id }}
        client-secret: ${{ inputs.client-secret }}
        tenant-id: ${{ inputs.tenant-id }}
        solution-file: ${{ inputs.solution-source-folder }}/${{ inputs.solution-name }}/managed/${{ inputs.solution-name }}_managed.zip
        stage-and-upgrade: true
        publish-changes: true
