name: 02-Deploy Travel Solution
# Deploy travelsolution to TEST and PRODUCTION environments
# Triggers when travelsolution is updated or manually

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'solutions/travelsolution/**'
  release:
    types: [created]

permissions:
  contents: write

jobs:
  deploy-travel-solution:
    uses: ./.github/workflows/shared-deployment-pipeline.yml
    with:
      solution_name: travelsolution
      BUILD_ENVIRONMENT_URL: 'https://mzhbuild.crm4.dynamics.com'
      TEST_ENVIRONMENT_URL: 'https://mzhtest.crm4.dynamics.com'
      PRODUCTION_ENVIRONMENT_URL: 'https://mzhprod.crm11.dynamics.com'
      CLIENT_ID: c07145b8-e4f8-48ad-8a7c-9fe5d3827e52
      TENANT_ID: d7d483b3-60d3-4211-a15e-9c2a090d2136      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
