name: 02-Deploy Travel Solution
# Deploy travelsolution to TEST and PRODUCTION environments
# Triggers when travelsolution is updated or manually

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'solutions/travelsolution/**'
  release:
    types: [created]

permissions:
  contents: write

jobs:
  deploy-travel:
    uses: ./.github/workflows/shared-deployment-pipeline.yml
    with:
      solution_name: travelsolution    
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
