name: 03-Deploy Coffee Shop Solution
# Deploy coffeeshop to TEST and PRODUCTION environments  
# Triggers when coffeeshop is updated or manually

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'solutions/coffeeshop/**'

permissions:
  contents: write

jobs:
  coffeeshop:
    uses: ./.github/workflows/shared-deployment-pipeline.yml
    with:
      solution_name: coffeeshop   
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
