name: 03-Deploy Coffee Shop Solution
# Deploy coffeeshop to TEST and PRODUCTION environments  
# Triggers when coffeeshop is updated or manually

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'solutions/coffeeshop/**'

permissions:
  contents: write

jobs:
  deploy-coffeeshop-solution:
    uses: ./.github/workflows/shared-deployment-pipeline.yml
    with:
      solution_name: coffeeshop
      BUILD_ENVIRONMENT_URL: ${{ vars.BUILD_ENVIRONMENT_URL }}
      TEST_ENVIRONMENT_URL: ${{ vars.TEST_ENVIRONMENT_URL }}
      PRODUCTION_ENVIRONMENT_URL: ${{ vars.PRODUCTION_ENVIRONMENT_URL }}
      CLIENT_ID: ${{ vars.CLIENT_ID }}
      TENANT_ID: ${{ vars.TENANT_ID }}      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
