name: 02-Deploy Core Solution
# Deploy core to TEST and PRODUCTION environments
# Triggers when core is updated or manually

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'solutions/core/**'

permissions:
  contents: write

jobs:
  deploy-core:
    uses: ./.github/workflows/shared-deployment-pipeline.yml
    with:
      solution_name: core    
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
