name: 04-Upgrade Coffee Shop Solution
# Upgrade coffeeshop to TEST and PRODUCTION environments  
# Triggers when coffeeshop is updated or manually

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'solutions/coffeeshop/**'

permissions:
  contents: write

jobs:
  upgrade-coffeeshop-solution:
    uses: ./.github/workflows/shared-upgrade-pipeline.yml
    with:
      solution_name: coffeeshop   
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
