name: Deploy Coffee Shop Solution
# Deploy coffeeshop to TEST and PRODUCTION environments  
# Triggers when coffeeshop is updated or manually

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: 
      - 'solutions/coffeeshop/**'

permissions:
  contents: write

jobs:
  deploy-coffeeshop-solution:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      solution_name: coffeeshop
      BUILD_ENVIRONMENT_URL: 'https://mzhbuild.crm4.dynamics.com'
      TEST_ENVIRONMENT_URL: 'https://mzhtest.crm4.dynamics.com'
      PRODUCTION_ENVIRONMENT_URL: 'https://mzhprod.crm11.dynamics.com'
      CLIENT_ID: c07145b8-e4f8-48ad-8a7c-9fe5d3827e52
      TENANT_ID: d7d483b3-60d3-4211-a15e-9c2a090d2136      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
