name: Manual Solution Upgrade
# Manual workflow to upgrade any solution to TEST and PRODUCTION environments  
# Can be triggered manually with solution selection

run-name: Upgrade ${{ github.event.inputs.solution_name }} to ${{ github.event.inputs.target_environment }}

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Which solution to upgrade?'
        required: true
        type: choice
        options:
          - travelsolution
          - coffeeshop
        default: 'coffeeshop'
      target_environment:
        description: 'Which environment to upgrade?'
        required: true
        type: choice
        options:
          - TEST
          - UAT
          - PRODUCTION
          - ALL
        default: 'TEST'

permissions:
  contents: write

jobs:
  upgrade-solution:
    uses: ./.github/workflows/shared-deployment-pipeline.yml
    with:
      solution_name: ${{ github.event.inputs.solution_name }}
      solution_outbound_folder: 'out/solutions/'
      solution_source_folder: 'solutions/'
      upgrade_mode: 'upgrade'
      target_environment: ${{ github.event.inputs.target_environment }}
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
