name: Power Platform Simple Test

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Solution name'
        required: true
        default: 'testsolution'

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Echo solution name
      run: echo "Solution name is ${{ github.event.inputs.solution_name }}"
